[package]
name = "netburrow-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "NetBurrow"
path = "src/main.rs"

[dependencies]
netburrow-core.workspace = true
serde.workspace = true
serde_json.workspace = true
eframe = { version = "=0.35.0", default-features = false, features = ["default_fonts", "glow"] }
zip = { version = "=8.2.0", default-features = false, features = ["deflate-flate2"] }
flate2 = { version = "=1.1.9", default-features = false, features = ["rust_backend"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_UI_Controls_Dialogs", "Win32_Networking_WinHttp"] }
